
name: Test application

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '15'
        cache: 'yarn'

    - name: Install yarn
      run: yarn install

    - name: Test
      run: yarn run test
      